### ISSUE TITLE
Mocha tests fail with any version of Chai more recent than 0.1.1

### ISSUE THREAD

**Issue by emilecantin** [geddski/amd-testing#3]
Mocha tests fail if Chai is updated beyond 0.1.1. The problem is that the 'expect' function is not defined in the tests' scope.

I believe the source of the problem is this change in Chai: https://github.com/chaijs/chai/commit/a7ee9b6bd2d744c1810df7fa031f8403952c4d07

Is there a way to keep assertions working with a recent version of Chai?

It would also be nice if there was documentation on how to make some functions / objects accessible in tests (like describe / it).

**Comment by geddski** [comment]
I'll update Chai and see if I can't get the example working again. Sorry for the delay!

**Comment by emilecantin** [comment]
I don't use AMD-testing anymore, so I'll go ahead and close the issue.
